# Generated by Django 4.2 on 2023-04-29 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='personalizacion_predefinida',
        ),
    ]
