# Generated by Django 4.2 on 2023-04-29 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0009_remove_imagenpersonalizacion_persopredefinida_and_more'),
        ('pedido', '0002_remove_detallepedido_personalizacion_predefinida'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='personalizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizacion.personalizacion'),
        ),
    ]
