# Generated by Django 4.2 on 2023-04-30 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0010_remove_personalizacion_producto'),
        ('pedido', '0003_detallepedido_personalizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='cliente',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='mensaje_personalizado',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='precio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='personalizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacion.personalizacion'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=100),
        ),
    ]
