# Generated by Django 4.2 on 2023-05-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_alter_detallepedido_options_alter_pedido_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='transaction_id',
            field=models.CharField(default=1684274236.617486, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='webpay_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
