# Generated by Django 4.2 on 2023-07-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_pedido_transaction_id_pedido_webpay_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='transaction_id',
            field=models.CharField(default='6528724314', max_length=100),
        ),
    ]
