# Generated by Django 4.2 on 2023-07-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0021_alter_pedido_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='transaction_id',
            field=models.CharField(default='6103223556', max_length=100),
        ),
    ]
