# Generated by Django 4.2 on 2023-04-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_remove_producto_imagen_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img_principal',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
