# Generated by Django 4.2 on 2023-04-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_img_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenproducto',
            name='principal',
        ),
    ]
