# Generated by Django 4.2 on 2023-04-28 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_producto_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img_principal',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='personalizable',
            field=models.BooleanField(default=False, verbose_name='¿Es personalizable?'),
        ),
    ]
