# Generated by Django 4.2 on 2023-04-29 21:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_alter_producto_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='aviso_personalizacion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Aviso de personalización'),
        ),
    ]
