# Generated by Django 4.2 on 2023-04-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_producto_aviso_personalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='aviso',
            field=models.BooleanField(default=False, verbose_name='¿Mostrar aviso de personalización?'),
        ),
    ]
