# Generated by Django 4.2 on 2023-07-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0012_producto_descripcion_corta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_vendidos',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
