# Generated by Django 4.2 on 2023-04-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgPerso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_perso', models.ImageField(blank=True, upload_to='personalizacion')),
            ],
        ),
        migrations.RemoveField(
            model_name='personalizacion',
            name='img_perso',
        ),
        migrations.AddField(
            model_name='personalizacion',
            name='img_perso',
            field=models.ManyToManyField(blank=True, to='personalizacion.imgperso'),
        ),
    ]
