# Generated by Django 4.2 on 2023-04-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0002_imgperso_remove_personalizacion_img_perso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizacion',
            name='img_perso',
        ),
        migrations.DeleteModel(
            name='ImgPerso',
        ),
        migrations.AddField(
            model_name='personalizacion',
            name='img_perso',
            field=models.ImageField(blank=True, upload_to='personalizacion'),
        ),
    ]
