# Generated by Django 4.2 on 2023-04-29 01:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0005_personalizacion_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizacionPredefinida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='personalizacion',
            name='img_perso',
        ),
        migrations.CreateModel(
            name='ImagenPersonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='personalizacion')),
                ('persoPredefinida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizacion.personalizacionpredefinida')),
                ('personalizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizacion.personalizacion')),
            ],
            options={
                'verbose_name': 'Imagen Personalizacion',
                'verbose_name_plural': 'Imagenes Personalizacion',
            },
        ),
    ]
