# Generated by Django 4.2 on 2023-04-29 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_alter_producto_fecha_creacion_and_more'),
        ('personalizacion', '0006_personalizacionpredefinida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacionpredefinida',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='producto.producto'),
        ),
    ]
