# Generated by Django 4.2 on 2023-04-30 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0009_remove_imagenpersonalizacion_persopredefinida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizacion',
            name='producto',
        ),
    ]
